package App.Modele;

// Generated 31 mars 2012 16:09:28 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AuthenticatedUser generated by hbm2java
 */
@Entity
@Table(name = "authenticated_user", catalog = "hibernate")
public class AuthenticatedUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1362255879350704302L;
	private String username;
	private String password;
	private String mail;
	private String firstname;
	private String lastname;
	private String bio;
	private String picture;
	private String website;
	private String socialnetwork;
	private boolean visibilitytrackrec;
	private boolean vsibilityownlibrary;
	private Set<Field> fields = new HashSet<Field>(0);
	private Set<Updatehistory> updatehistories = new HashSet<Updatehistory>(0);
	private Set<Evaluation> evaluations = new HashSet<Evaluation>(0);
	private Set<Record> records = new HashSet<Record>(0);
	private Set<Playlist> playlists = new HashSet<Playlist>(0);
	private Set<OwnRecord> ownRecords = new HashSet<OwnRecord>(0);
	private Set<Comment> comments = new HashSet<Comment>(0);

	public AuthenticatedUser() {
	}

	public AuthenticatedUser(String username, String password, String mail,
			String firstname, String lastname, boolean visibilitytrackrec,
			boolean vsibilityownlibrary) {
		this.username = username;
		this.password = password;
		this.mail = mail;
		this.firstname = firstname;
		this.lastname = lastname;
		this.visibilitytrackrec = visibilitytrackrec;
		this.vsibilityownlibrary = vsibilityownlibrary;
	}

	public AuthenticatedUser(String username, String password, String mail,
			String firstname, String lastname, String bio, String picture,
			String website, String socialnetwork, boolean visibilitytrackrec,
			boolean vsibilityownlibrary, Set<Field> fields,
			Set<Updatehistory> updatehistories, Set<Evaluation> evaluations,
			Set<Record> records, Set<Playlist> playlists,
			Set<OwnRecord> ownRecords, Set<Comment> comments) {
		this.username = username;
		this.password = password;
		this.mail = mail;
		this.firstname = firstname;
		this.lastname = lastname;
		this.bio = bio;
		this.picture = picture;
		this.website = website;
		this.socialnetwork = socialnetwork;
		this.visibilitytrackrec = visibilitytrackrec;
		this.vsibilityownlibrary = vsibilityownlibrary;
		this.fields = fields;
		this.updatehistories = updatehistories;
		this.evaluations = evaluations;
		this.records = records;
		this.playlists = playlists;
		this.ownRecords = ownRecords;
		this.comments = comments;
	}

	@Id
	@Column(name = "username", unique = true, nullable = false, length = 12)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 12)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "mail", nullable = false, length = 25)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "firstname", nullable = false, length = 20)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", nullable = false, length = 20)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "bio", length = 100)
	public String getBio() {
		return this.bio;
	}

	public void setBio(String bio) {
		this.bio = bio;
	}

	@Column(name = "picture", length = 50)
	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	@Column(name = "website", length = 50)
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@Column(name = "socialnetwork", length = 50)
	public String getSocialnetwork() {
		return this.socialnetwork;
	}

	public void setSocialnetwork(String socialnetwork) {
		this.socialnetwork = socialnetwork;
	}

	@Column(name = "visibilitytrackrec", nullable = false)
	public boolean isVisibilitytrackrec() {
		return this.visibilitytrackrec;
	}

	public void setVisibilitytrackrec(boolean visibilitytrackrec) {
		this.visibilitytrackrec = visibilitytrackrec;
	}

	@Column(name = "vsibilityownlibrary", nullable = false)
	public boolean isVsibilityownlibrary() {
		return this.vsibilityownlibrary;
	}

	public void setVsibilityownlibrary(boolean vsibilityownlibrary) {
		this.vsibilityownlibrary = vsibilityownlibrary;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "authenticatedUser")
	public Set<Field> getFields() {
		return this.fields;
	}

	public void setFields(Set<Field> fields) {
		this.fields = fields;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "authenticatedUser")
	public Set<Updatehistory> getUpdatehistories() {
		return this.updatehistories;
	}

	public void setUpdatehistories(Set<Updatehistory> updatehistories) {
		this.updatehistories = updatehistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "authenticatedUser")
	public Set<Evaluation> getEvaluations() {
		return this.evaluations;
	}

	public void setEvaluations(Set<Evaluation> evaluations) {
		this.evaluations = evaluations;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "tracked_records", catalog = "hibernate", joinColumns = { @JoinColumn(name = "id_user", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_record", nullable = false, updatable = false) })
	public Set<Record> getRecords() {
		return this.records;
	}

	public void setRecords(Set<Record> records) {
		this.records = records;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "playlist_user", catalog = "hibernate", joinColumns = { @JoinColumn(name = "id_user", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_playlist", nullable = false, updatable = false) })
	public Set<Playlist> getPlaylists() {
		return this.playlists;
	}

	public void setPlaylists(Set<Playlist> playlists) {
		this.playlists = playlists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "authenticatedUser")
	public Set<OwnRecord> getOwnRecords() {
		return this.ownRecords;
	}

	public void setOwnRecords(Set<OwnRecord> ownRecords) {
		this.ownRecords = ownRecords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "authenticatedUser")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

}
