package app.model;


// Generated 31 mars 2012 16:09:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EvaluationId generated by hbm2java
 */
@Embeddable
public class EvaluationId implements java.io.Serializable {

	private String username;
	private String recordnumber;

	public EvaluationId() {
	}

	public EvaluationId(String username, String recordnumber) {
		this.username = username;
		this.recordnumber = recordnumber;
	}

	@Column(name = "username", nullable = false, length = 12)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "recordnumber", nullable = false, length = 20)
	public String getRecordnumber() {
		return this.recordnumber;
	}

	public void setRecordnumber(String recordnumber) {
		this.recordnumber = recordnumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EvaluationId))
			return false;
		EvaluationId castOther = (EvaluationId) other;

		return ((this.getUsername() == castOther.getUsername()) || (this
				.getUsername() != null && castOther.getUsername() != null && this
				.getUsername().equals(castOther.getUsername())))
				&& ((this.getRecordnumber() == castOther.getRecordnumber()) || (this
						.getRecordnumber() != null
						&& castOther.getRecordnumber() != null && this
						.getRecordnumber().equals(castOther.getRecordnumber())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37
				* result
				+ (getRecordnumber() == null ? 0 : this.getRecordnumber()
						.hashCode());
		return result;
	}

}
