package Modele;

// Generated 26 mars 2012 22:26:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FieldOwnedRecordsId generated by hbm2java
 */
@Embeddable
public class FieldOwnedRecordsId implements java.io.Serializable {

	private int idField;
	private String idOwnedRecord;

	public FieldOwnedRecordsId() {
	}

	public FieldOwnedRecordsId(int idField, String idOwnedRecord) {
		this.idField = idField;
		this.idOwnedRecord = idOwnedRecord;
	}

	@Column(name = "id_field", nullable = false)
	public int getIdField() {
		return this.idField;
	}

	public void setIdField(int idField) {
		this.idField = idField;
	}

	@Column(name = "id_owned_record", nullable = false, length = 12)
	public String getIdOwnedRecord() {
		return this.idOwnedRecord;
	}

	public void setIdOwnedRecord(String idOwnedRecord) {
		this.idOwnedRecord = idOwnedRecord;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FieldOwnedRecordsId))
			return false;
		FieldOwnedRecordsId castOther = (FieldOwnedRecordsId) other;

		return (this.getIdField() == castOther.getIdField())
				&& ((this.getIdOwnedRecord() == castOther.getIdOwnedRecord()) || (this
						.getIdOwnedRecord() != null
						&& castOther.getIdOwnedRecord() != null && this
						.getIdOwnedRecord()
						.equals(castOther.getIdOwnedRecord())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdField();
		result = 37
				* result
				+ (getIdOwnedRecord() == null ? 0 : this.getIdOwnedRecord()
						.hashCode());
		return result;
	}

}
