package Modele;

// Generated 26 mars 2012 22:26:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FieldOwnedRecords generated by hbm2java
 */
@Entity
@Table(name = "field_owned_records", catalog = "hibernate")
public class FieldOwnedRecords implements java.io.Serializable {

	private FieldOwnedRecordsId id;
	private Field field;
	private OwnRecord ownRecord;
	private int value;

	public FieldOwnedRecords() {
	}

	public FieldOwnedRecords(FieldOwnedRecordsId id, Field field,
			OwnRecord ownRecord, int value) {
		this.id = id;
		this.field = field;
		this.ownRecord = ownRecord;
		this.value = value;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idField", column = @Column(name = "id_field", nullable = false)),
			@AttributeOverride(name = "idOwnedRecord", column = @Column(name = "id_owned_record", nullable = false, length = 12)) })
	public FieldOwnedRecordsId getId() {
		return this.id;
	}

	public void setId(FieldOwnedRecordsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_field", nullable = false, insertable = false, updatable = false)
	public Field getField() {
		return this.field;
	}

	public void setField(Field field) {
		this.field = field;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "id_user", referencedColumnName = "id_user", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "id_owned_record", referencedColumnName = "id_record", nullable = false, insertable = false, updatable = false) })
	public OwnRecord getOwnRecord() {
		return this.ownRecord;
	}

	public void setOwnRecord(OwnRecord ownRecord) {
		this.ownRecord = ownRecord;
	}

	@Column(name = "value", nullable = false)
	public int getValue() {
		return this.value;
	}

	public void setValue(int value) {
		this.value = value;
	}

}
