package Modele;

// Generated 26 mars 2012 22:26:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OwnRecordId generated by hbm2java
 */
@Embeddable
public class OwnRecordId implements java.io.Serializable {

	private String idUser;
	private String idRecord;

	public OwnRecordId() {
	}

	public OwnRecordId(String idUser, String idRecord) {
		this.idUser = idUser;
		this.idRecord = idRecord;
	}

	@Column(name = "id_user", nullable = false, length = 12)
	public String getIdUser() {
		return this.idUser;
	}

	public void setIdUser(String idUser) {
		this.idUser = idUser;
	}

	@Column(name = "id_record", nullable = false, length = 20)
	public String getIdRecord() {
		return this.idRecord;
	}

	public void setIdRecord(String idRecord) {
		this.idRecord = idRecord;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OwnRecordId))
			return false;
		OwnRecordId castOther = (OwnRecordId) other;

		return ((this.getIdUser() == castOther.getIdUser()) || (this
				.getIdUser() != null && castOther.getIdUser() != null && this
				.getIdUser().equals(castOther.getIdUser())))
				&& ((this.getIdRecord() == castOther.getIdRecord()) || (this
						.getIdRecord() != null
						&& castOther.getIdRecord() != null && this
						.getIdRecord().equals(castOther.getIdRecord())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdUser() == null ? 0 : this.getIdUser().hashCode());
		result = 37 * result
				+ (getIdRecord() == null ? 0 : this.getIdRecord().hashCode());
		return result;
	}

}
