package Modele;

// Generated 26 mars 2012 22:26:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Playlist generated by hbm2java
 */
@Entity
@Table(name = "playlist", catalog = "hibernate")
public class Playlist implements java.io.Serializable {

	private Integer idPlaylist;
	private String name;
	private boolean visibility;
	private Set<AuthenticatedUser> authenticatedUsers = new HashSet<AuthenticatedUser>(
			0);
	private Set<Record> records = new HashSet<Record>(0);

	public Playlist() {
	}

	public Playlist(String name, boolean visibility) {
		this.name = name;
		this.visibility = visibility;
	}

	public Playlist(String name, boolean visibility,
			Set<AuthenticatedUser> authenticatedUsers, Set<Record> records) {
		this.name = name;
		this.visibility = visibility;
		this.authenticatedUsers = authenticatedUsers;
		this.records = records;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_playlist", unique = true, nullable = false)
	public Integer getIdPlaylist() {
		return this.idPlaylist;
	}

	public void setIdPlaylist(Integer idPlaylist) {
		this.idPlaylist = idPlaylist;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "visibility", nullable = false)
	public boolean isVisibility() {
		return this.visibility;
	}

	public void setVisibility(boolean visibility) {
		this.visibility = visibility;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "playlist_user", catalog = "hibernate", joinColumns = { @JoinColumn(name = "id_playlist", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_user", nullable = false, updatable = false) })
	public Set<AuthenticatedUser> getAuthenticatedUsers() {
		return this.authenticatedUsers;
	}

	public void setAuthenticatedUsers(Set<AuthenticatedUser> authenticatedUsers) {
		this.authenticatedUsers = authenticatedUsers;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "playlist_records", catalog = "hibernate", joinColumns = { @JoinColumn(name = "id_playlist", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_record", nullable = false, updatable = false) })
	public Set<Record> getRecords() {
		return this.records;
	}

	public void setRecords(Set<Record> records) {
		this.records = records;
	}

}
