package Modele;

// Generated 26 mars 2012 22:26:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Updatehistory generated by hbm2java
 */
@Entity
@Table(name = "updatehistory", catalog = "hibernate")
public class Updatehistory implements java.io.Serializable {

	private UpdatehistoryId id;
	private AuthenticatedUser authenticatedUser;
	private Record record;
	private String title;
	private String pressinfo;
	private int numdisk;
	private String type;
	private Date historydate;

	public Updatehistory() {
	}

	public Updatehistory(UpdatehistoryId id,
			AuthenticatedUser authenticatedUser, Record record, String title,
			String pressinfo, int numdisk, String type, Date historydate) {
		this.id = id;
		this.authenticatedUser = authenticatedUser;
		this.record = record;
		this.title = title;
		this.pressinfo = pressinfo;
		this.numdisk = numdisk;
		this.type = type;
		this.historydate = historydate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "username", column = @Column(name = "username", nullable = false, length = 12)),
			@AttributeOverride(name = "recordnumber", column = @Column(name = "recordnumber", nullable = false, length = 20)) })
	public UpdatehistoryId getId() {
		return this.id;
	}

	public void setId(UpdatehistoryId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "username", nullable = false, insertable = false, updatable = false)
	public AuthenticatedUser getAuthenticatedUser() {
		return this.authenticatedUser;
	}

	public void setAuthenticatedUser(AuthenticatedUser authenticatedUser) {
		this.authenticatedUser = authenticatedUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "recordnumber", nullable = false, insertable = false, updatable = false)
	public Record getRecord() {
		return this.record;
	}

	public void setRecord(Record record) {
		this.record = record;
	}

	@Column(name = "title", nullable = false, length = 20)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "pressinfo", nullable = false, length = 50)
	public String getPressinfo() {
		return this.pressinfo;
	}

	public void setPressinfo(String pressinfo) {
		this.pressinfo = pressinfo;
	}

	@Column(name = "numdisk", nullable = false)
	public int getNumdisk() {
		return this.numdisk;
	}

	public void setNumdisk(int numdisk) {
		this.numdisk = numdisk;
	}

	@Column(name = "type", nullable = false, length = 20)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "historydate", nullable = false, length = 19)
	public Date getHistorydate() {
		return this.historydate;
	}

	public void setHistorydate(Date historydate) {
		this.historydate = historydate;
	}

}
